# Generated by Django 4.2.28 on 2026-03-03 04:03

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('commercial', 'Коммерческая'), ('land', 'Участок')], db_index=True, max_length=20, verbose_name='Тип')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Комнат')),
                ('area', models.FloatField(verbose_name='Площадь (м²)')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('floors_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этажей в доме')),
                ('furniture', models.BooleanField(default=True, verbose_name='Мебель')),
                ('technique', models.BooleanField(default=True, verbose_name='Техника')),
                ('egrn_number', models.CharField(help_text='Выписка из Единого государственного реестра недвижимости', max_length=50, unique=True, verbose_name='Номер ЕГРН')),
                ('egrn_file', models.FileField(help_text='Загрузите выписку из ЕГРН', upload_to='egrn/%Y/%m/', verbose_name='Файл ЕГРН')),
                ('egrn_verified', models.BooleanField(default=False, verbose_name='ЕГРН проверен')),
                ('moderation_status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('archived', 'В архиве')], db_index=True, default='pending', max_length=20, verbose_name='Статус модерации')),
                ('moderation_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Опубликовано')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('user_type', models.CharField(choices=[('tenant', 'Арендатор'), ('landlord', 'Арендодатель'), ('moderator', 'Модератор'), ('admin', 'Администратор')], db_index=True, default='tenant', max_length=20, verbose_name='Тип пользователя')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+79991234567' или '89991234567'", regex='^\\+?7?\\d{10,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('block_reason', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ViewingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_date', models.DateTimeField(verbose_name='Желаемая дата')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('completed', 'Состоялся'), ('cancelled', 'Отменен')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('response_message', models.TextField(blank=True, verbose_name='Ответ')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Подтвержденная дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlackApp.property')),
                ('tenant', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос на просмотр',
                'verbose_name_plural': 'Запросы на просмотр',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_property_types', models.TextField(default='[]', help_text='Например: ["apartment", "house"]', verbose_name='Предпочитаемые типы жилья')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Максимальная цена')),
                ('min_rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Минимум комнат')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Холост/Не замужем'), ('married', 'Женат/Замужем'), ('divorced', 'Разведен')], max_length=20, verbose_name='Семейное положение')),
                ('has_children', models.BooleanField(default=False, verbose_name='Есть дети')),
                ('employment', models.CharField(blank=True, max_length=200, verbose_name='Место работы')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ежемесячный доход')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль арендатора',
                'verbose_name_plural': 'Профили арендаторов',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Промодерирован')),
                ('author', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlackApp.property')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/', verbose_name='Фото')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='properties/thumbnails/%Y/%m/', verbose_name='Миниатюра')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='BlackApp.property')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['-is_main', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='moderator',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['moderator', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('total_properties', models.PositiveIntegerField(default=0, verbose_name='Всего объектов')),
                ('active_properties', models.PositiveIntegerField(default=0, verbose_name='Активных объектов')),
                ('total_bookings', models.PositiveIntegerField(default=0, verbose_name='Всего бронирований')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['moderator', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_landlords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль арендодателя',
                'verbose_name_plural': 'Профили арендодателей',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlackApp.property')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Паспорт'), ('egrn', 'Выписка ЕГРН'), ('ownership', 'Свидетельство о собственности'), ('contract', 'Договор аренды'), ('other', 'Другое')], db_index=True, max_length=20, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Проверен')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверен')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['moderator', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='BlackApp_us_user_ty_ee4567_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='BlackApp_us_date_jo_35cd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingrequest',
            index=models.Index(fields=['tenant', 'status'], name='BlackApp_vi_tenant__83bfe4_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingrequest',
            index=models.Index(fields=['property', 'status'], name='BlackApp_vi_propert_a6a7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingrequest',
            index=models.Index(fields=['desired_date'], name='BlackApp_vi_desired_7fc728_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['landlord', 'rating'], name='BlackApp_re_landlor_c59371_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='BlackApp_re_created_42daea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'property')},
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_main'], name='BlackApp_pr_propert_11228e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['moderation_status', 'published_at'], name='BlackApp_pr_moderat_ecfee8_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'price'], name='BlackApp_pr_propert_a5a40c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rooms', 'area'], name='BlackApp_pr_rooms_a9d128_idx'),
        ),
        migrations.AddIndex(
            model_name='landlordprofile',
            index=models.Index(fields=['rating'], name='BlackApp_la_rating_6ec374_idx'),
        ),
        migrations.AddIndex(
            model_name='landlordprofile',
            index=models.Index(fields=['is_verified'], name='BlackApp_la_is_veri_9be949_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='BlackApp_fa_user_id_6daa38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'property')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'doc_type'], name='BlackApp_do_user_id_2435a0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_verified', 'uploaded_at'], name='BlackApp_do_is_veri_910373_idx'),
        ),
    ]
