# Generated by Django 4.2.28 on 2026-03-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='furniture',
        ),
        migrations.RemoveField(
            model_name='property',
            name='technique',
        ),
        migrations.AddField(
            model_name='property',
            name='allows_children',
            field=models.BooleanField(default=True, verbose_name='Можно с детьми'),
        ),
        migrations.AddField(
            model_name='property',
            name='allows_pets',
            field=models.BooleanField(default=False, verbose_name='Можно с животными'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_appliances',
            field=models.BooleanField(default=False, verbose_name='С техникой'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_furniture',
            field=models.BooleanField(default=False, verbose_name='С мебелью'),
        ),
    ]
