# Generated by Django 4.2.28 on 2026-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackApp', '0002_remove_property_furniture_remove_property_technique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='egrn_file',
            field=models.FileField(help_text='Загрузите выписку из ЕГРН', upload_to='temp/egrn/%Y/%m/', verbose_name='Файл ЕГРН'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='temp/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='temp/thumbnails/%Y/%m/%d/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='viewingrequest',
            name='desired_date',
            field=models.DateField(verbose_name='Желаемая дата'),
        ),
    ]
