# Generated by Django 4.2.28 on 2026-04-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackApp', '0004_booking_delete_viewingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='separate_bathroom',
            field=models.BooleanField(default=False, verbose_name='Раздельный санулзел'),
        ),
        migrations.AlterField(
            model_name='property',
            name='allows_children',
            field=models.BooleanField(default=False, verbose_name='Можно с детьми'),
        ),
    ]
