# Generated by Django 4.2.28 on 2026-04-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackApp', '0005_property_separate_bathroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
