# Generated by Django 4.2.28 on 2026-04-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackApp', '0006_landlordprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
